$$SHORTCODE$$.C.APP_ID               = $$SHORTCODE$$.VALUE_NOT_INITIALIZED;
$$SHORTCODE$$.C.APP_NAME             = $$SHORTCODE$$.VALUE_NOT_INITIALIZED;
$$SHORTCODE$$.C.DIRNAME_PREFERENCES  = $$SHORTCODE$$.VALUE_NOT_INITIALIZED;
$$SHORTCODE$$.C.FILENAME_PREFERENCES = $$SHORTCODE$$.VALUE_NOT_INITIALIZED;
